First commit to the fibonacci without recursive task
ZabielJR/FirstRepoo pull request #20
Opened 2017-04-10 09:55 UTC by ZabielJR

2017-04-11 13:00 UTC, dabrowskisoftware requested changes
It's working but... a, b, c?

Please start using descriptive names for variables.

2017-04-11 13:00 UTC, dabrowskisoftware commented on fibonacci-without-recursive.js
> +        c = 1;
It this line necessary?

2017-04-12 10:11 UTC, ZabielJR commented on fibonacci-without-recursive.js
> +        c = 1;
Yes, because the value of variable has to be always the same in this task. Of cours this is my opinion

2017-04-12 10:31 UTC, dabrowskisoftware commented on fibonacci-without-recursive.js
> +        c = 1;
Before you write something like this, you should remove the line and check if anything has changed. I can guarantee you that you don't need this line. Please, remove it and try to understand why you don't need it.

2017-04-14 09:58 UTC, dabrowskisoftware requested changes

2017-04-14 09:58 UTC, dabrowskisoftware commented on fibonacci-without-recursive.js
> +        nextNumber = currentNumber + previousNumber;
This variable is not declared.

2017-04-14 10:44 UTC, dabrowskisoftware approved these changes

2017-04-14 10:44 UTC, merged