First commit to the geoMean task
ZabielJR/FirstRepoo pull request #25
Opened 2017-04-15 09:16 UTC by ZabielJR

2017-04-15 16:29 UTC, dabrowskisoftware reviewed
It's ok but it's a perfect case for Array.reduce:

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

Please, change your solution to use Array.reduce.

2017-04-15 16:29 UTC, dabrowskisoftware commented on geoMean.js
> +    let multiples = array[0];
You could set it to 1 in the beginning and then use a normal for loop starting from the first element. But this is ok as well.

2017-04-15 16:29 UTC, dabrowskisoftware commented on geoMean.js
> +    let multiples = array[0];
multiples is not a good name for a number. It should be called `product.`

2017-04-18 22:23 UTC, dabrowskisoftware commented on geoMean.js
> +  return Math.pow(array.reduce(function(prev, next) {
Everything is ok except one parameter name.

According to this:

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

the first parameter is not a previous element. It's an accumulator.

2017-04-19 09:02 UTC, dabrowskisoftware requested changes

2017-04-19 09:02 UTC, dabrowskisoftware commented on geoMean.js
> +  return Math.pow(array.reduce(function(acc, next) {
What is acc? Acceptance? Accelerator? Name it with no shortcuts! :)

2017-04-19 14:08 UTC, ZabielJR commented on geoMean.js
> +  return Math.pow(array.reduce(function(acc, next) {
Account 🥇  sorry about that

2017-04-19 14:15 UTC, dabrowskisoftware approved these changes

2017-04-19 14:15 UTC, merged